version: 2.0
jobs:
  build-and-test:
    docker:
      - image: circleci/node:13.13.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6'
      - restore_cache:
          key: dependency=cache={{ checksum "package-lock.json" }}
      - run:
          name: install-npm-modules
          command: 'npm install'
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths: 
          - ./node_modules
      - run:
          name: test
          command: 'npm run test:ci'
  build-deploy-prod:
    docker:
      - image: circleci/node:13.13.0
    steps:
      - checkout
      - run:
          name: deploy-heroku-prod
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PIPELINE-prod.git master
workflows:
  version: 2
  build-test-deploy-prod:
    jobs:
      - build-and-test:
            filters:
              branches:
                only: master
      - build-deploy-prod:
            requires:
              - build-and-test
            filters:
              branches:
                only: master
      
